name: Docker

on: [push, pull_request]

jobs:
  
  clean-up:
    name: Clean up
    runs-on: ubuntu-latest
    steps:

      - name: Clean up
        run: rm -rf *
        
  docker-ros:
    runs-on: ubuntu-latest
    needs: clean-up
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          submodules: true
          
      - uses: robinraju/release-downloader@v1.8
        name: Download PythonAPI
        with:
          repository: carla-compose/carla-simulator
          tag: v0.9.15
          fileName: PythonAPI.tar.gz
          extract: true
          out-file-path: docker/additional-files
          
      - name: Remove PythonAPI.tar.gz
        run: rm docker/additional-files/PythonAPI.tar.gz

      - uses: ika-rwth-aachen/docker-ros@v1.4.0
        name: Run docker-ros pipeline
        with:
          base-image: rwthika/ros2:humble
          command: ros2 launch carla_ros_bridge carla_ros_bridge.launch.py
          target: run
          platform: amd64
          registry: docker.io
          registry-user: ${{ secrets.DOCKER_USERNAME }}
          registry-password: ${{ secrets.DOCKER_PASSWORD }}
          image-name: rwthika/carla-ros-bridge
          image-tag: ros2
          enable-push-as-latest: true
          enable-checkout: false
